### ISSUE TITLE
Page action doesn't work

### ISSUE THREAD

**Issue by Madcliff** [Luzifer/streamdeck#4]
So it seems that the page swapping action is not working.

**Comment by Luzifer** [comment]
Works fine for me… Please provide more details what exactly isn't working…

**Comment by Madcliff** [comment]
`      24:
        display:
          type: exec
          attributes:
            caption: Page 2
            command: ["/usr/bin/date", "+%H:%M:%S"]
            env:
              MYVAR: "myvalue"
            font-size: 20.0
            interval: 1
          actions:
          - type: page
            attributes:
              name: gaming`

Does not open the page called gaming

**Comment by Luzifer** [comment]
Your indentation is broken:

```yaml
      5:
        display:
          type: image
          attributes:
            path: /home/luzifer/.config/streamdeck/images/twitch.png
        actions:
          - type: page
            attributes:
              name: twitch
```

`actions` must be on the same level as `display`, not nested below.
